app:
  port: 3001
  redis_url: redis
  hub:
    privkey_path: keys/key.pem
    pubkey_path: keys/pubkey.pem
    cert_path: keys/cert.pem
    rootca_cert_path: keys/rootCA.crt
    host: 0.0.0.0
    port: 4433
