services:
  botsocean:
    build: .
    image: yadsendewlung/botsocean:latest
    container_name: botsocean
    restart: always
    ports:
      - "3000:3000"
      - "4433:4433/tcp"
      - "4433:4433/udp"
    # depends_on:
      # - mongodb
    volumes:
      - ./config.yml:/usr/src/app/config.yml
      - ./keys:/usr/src/app/keys

  # mongodb:
  #   image: mongo:6.0
  #   container_name: mongodb
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_DATABASE: money_printer
  #   volumes:
  #     - mongo_data:/data/db
  #   restart: always

volumes:
  mongo_data:
