services:
  botsocean:
    build: .
    image: yadsendewlung/botsocean:latest
    container_name: botsocean
    restart: always
    ports:
      - "3000:3000" # Maps the host port 3000 to the container port 3000
    depends_on:
      - mongodb # Ensure the MongoDB service starts before this service
    volumes:
      - ./config.yml:/usr/src/app/config.yml

  # mongodb:
  #   image: mongo:6.0
  #   container_name: mongodb
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_DATABASE: money_printer
  #   volumes:
  #     - mongo_data:/data/db
  #   restart: always

volumes:
  mongo_data:
