services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.redis-data:/data
  botsocean:
    build: .
    image: yadsendewlung/botsocean:latest
    container_name: botsocean
    restart: always
    ports:
      - "4431:4431"
      - "4433:4433/tcp"
      - "4433:4433/udp"
    depends_on:
      - redis
    volumes:
      - ./config.yml:/usr/src/app/config.yml
      - ./keys:/usr/src/app/keys
